[build]
builder = "NIXPACKS"

[deploy]
startCommand = "yarn workspace server start"
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 1

[deploy.resources]
cpu = 0.5
memory = 512

[deploy.networking]
servicePort = 8080